const eatermonStats = [
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 30,
        defense: 5,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 30,
        defense: 40,
        evasiveness: 100,
        speed: 7, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
    {
        hp: 10, 
        attack: 10,
        defense: 10,
        evasiveness: 100,
        speed: 5, 
    },
]
